SUNNY-PJ/Backend

src/main/java/com/sunny/backend/service/community/CommunityService.java

add Transactional
* 2023-09-12
failed to lazily initialize a collection of role error 해결하기 위해 추가

[update] add Transactional

---

src/main/java/com/sunny/backend/controller/CommentController.java
src/main/java/com/sunny/backend/controller/CommunityController.java
src/main/java/com/sunny/backend/controller/CompetitionController.java
src/main/java/com/sunny/backend/controller/ConsumptionController.java
src/main/java/com/sunny/backend/controller/FriendsController.java
src/main/java/com/sunny/backend/controller/SaveController.java
src/main/java/com/sunny/backend/controller/ScrapController.java
src/main/java/com/sunny/backend/service/ScrapService.java
src/main/java/com/sunny/backend/service/comment/CommentService.java
src/main/java/com/sunny/backend/service/community/CommunityService.java
src/main/java/com/sunny/backend/service/consumption/ConsumptionService.java
src/main/java/com/sunny/backend/service/save/SaveService.java
src/main/java/com/sunny/backend/user/controller/AuthController.java

Dev -> Main (Swagger 정리)
* 2023-09-16
Swagger 정리

Dev - > Main (Merge)

---

src/main/java/com/sunny/backend/user/Users.java

[update] community fetch update
* 2023/09/18
community fetch update (lazy->eagar)

[update] community fetch update

---

src/main/java/com/sunny/backend/user/Users.java

[update] consumptionList,commentList fetch type change
* 2023/09/18
consumptionList,commentList fetch type change (lazy->eager)

[update] consumptionList,commentList fetch type change

---

src/main/java/com/sunny/backend/entity/Community.java
src/main/java/com/sunny/backend/service/community/CommunityService.java
src/main/java/com/sunny/backend/service/save/SaveService.java

[update] add response message
* 2023/09/18
add response message

[update] add response message

---

src/main/java/com/sunny/backend/user/Users.java

[update] fetch type
* 2023/09/18
[update] fetch type

[update] fetch type

---

src/main/java/com/sunny/backend/service/consumption/ConsumptionService.java
src/main/java/com/sunny/backend/user/Users.java

[update] solved MultipleBagFetchException
* 2023/09/18
solved MultipleBagFetchException

[update] solved MultipleBagFetchException

---

src/main/java/com/sunny/backend/user/Users.java

[update] fetch mode
*2023/09/18
fetch mode

[update] fetch mode

---

src/main/java/com/sunny/backend/user/Users.java

[update] change fetch mode
* 2023/09/18
[update] change fetch mode

[update] change fetch mode

---

src/main/java/com/sunny/backend/service/comment/CommentService.java
src/main/java/com/sunny/backend/service/community/CommunityService.java
src/main/java/com/sunny/backend/service/consumption/ConsumptionService.java
src/main/java/com/sunny/backend/service/save/SaveService.java
src/main/java/com/sunny/backend/user/Users.java

[update] fixed error
* 2023/09/18
[update] fixed error
- Lazy 로딩 초기화 부분 수정 (댓글 , 게시글 ,소비)
- 게시글 사진 수정 response 값 수정

[update] fixed error

---

src/main/java/com/sunny/backend/config/SwaggerConfig.java
src/main/java/com/sunny/backend/controller/ScrapController.java
src/main/java/com/sunny/backend/service/CompetitionService.java
src/main/java/com/sunny/backend/service/FriendsService.java
src/main/java/com/sunny/backend/user/controller/AuthController.java

swagger 정리 

---

src/main/java/com/sunny/backend/controller/FcmController.java
src/main/java/com/sunny/backend/dto/request/FcmRequestDto.java
src/main/java/com/sunny/backend/entity/FcmMessage.java
src/main/java/com/sunny/backend/service/FCMService.java

feature -> merger / [feat] add FCM

---

src/main/java/com/sunny/backend/dto/response/community/CommunityResponse.java
src/main/java/com/sunny/backend/service/KaKaoService.java

modify CommunityResponse
* 2023/10/10
CommunityResponse에 게시글 id 값 반환하도록 수정

[update] modify CommunityResponse

---

src/main/java/com/sunny/backend/controller/SaveController.java

절약 목표 조회 기능 추가 
* 2023-11-04
- 절약 목표 조회 기능 추가 
- 절약(save) 엔티티 수정
→ 절약 내용 컬럼 추가

[update] 절약 목표 조회 ver2

---

src/main/java/com/sunny/backend/controller/CommunityController.java
src/main/java/com/sunny/backend/repository/community/CommunityRepositoryImpl.java

커뮤니티 게시판 정렬 조건 수정
* 2023-11-04
커뮤니티 게시판 정렬 조건 수정
- 카테고리
- 조회순, 최신순
- 검색 키워드

[fix] 커뮤니티 게시판 정렬 조건 수정

---

src/main/java/com/sunny/backend/common/DatetimeUtil.java
src/main/java/com/sunny/backend/controller/CommunityController.java
src/main/java/com/sunny/backend/controller/MyPageController.java
src/main/java/com/sunny/backend/dto/request/consumption/ConsumptionRequest.java
src/main/java/com/sunny/backend/dto/response/community/CommunityResponse.java
src/main/java/com/sunny/backend/entity/Community.java
src/main/java/com/sunny/backend/service/MyPageService.java
src/main/java/com/sunny/backend/service/community/CommunityService.java
src/main/java/com/sunny/backend/service/consumption/ConsumptionService.java

community 등록/수정 시간 형식 수정
* 2023-12-20
community 등록/수정 시간 형식 수정
- 00분전 , 00 시간전 등의 형식으로 수정

[fix] community 등록/수정 시간 형식 수정

---

src/main/java/com/sunny/backend/common/ErrorCode.java
src/main/java/com/sunny/backend/controller/MyPageController.java
src/main/java/com/sunny/backend/service/KaKaoService.java
src/main/java/com/sunny/backend/service/MyPageService.java
src/main/java/com/sunny/backend/user/repository/UserRepository.java

닉네임 중복 방지 기능 추가
* 2023-12-20
닉네임 중복 방지 기능 추가

[fix] 닉네임 중복 방지 기능

---

src/main/java/com/sunny/backend/common/DatetimeUtil.java
src/main/java/com/sunny/backend/dto/response/community/CommunityResponse.java
src/main/java/com/sunny/backend/service/community/CommunityService.java

community response 수정 시간 업데이트
* 2023-12-26
- community response 수정 시간 업데이트

[fix] community response

---

src/main/java/com/sunny/backend/common/DatetimeUtil.java

community response createdAt 수정
* 2023-12-26
- community response createdAt 값 음수로 나와서 수정

[fix] community response createdAt 수정

---

src/main/java/com/sunny/backend/common/DatetimeUtil.java

Updated based on creation time Seoul
* 2023-12-26
- 생성시간 및 수정 시간이 서버에 올리면 음수 값이 뜸 -> 서울 기준으로 시간을 잡아서 업데이트 하도록 수정

[fix] Updated based on creation time Seoul

---

src/main/java/com/sunny/backend/common/DatetimeUtil.java
src/main/java/com/sunny/backend/controller/CommunityController.java
src/main/java/com/sunny/backend/dto/response/community/CommunityResponse.java

community responnse
* 2023-12-26
- community responnse post-get 업데이트

[fix] community responnse

---

docker-compose.yml
src/main/java/com/sunny/backend/common/ErrorCode.java
src/main/java/com/sunny/backend/controller/CommentController.java
src/main/java/com/sunny/backend/dto/response/comment/CommentResponse.java
src/main/java/com/sunny/backend/dto/response/community/CommunityResponse.java
src/main/java/com/sunny/backend/repository/comment/CommentRepository.java
src/main/java/com/sunny/backend/repository/community/CommunityRepositoryImpl.java
src/main/java/com/sunny/backend/service/MyPageService.java
src/main/java/com/sunny/backend/service/comment/CommentService.java
src/main/java/com/sunny/backend/service/community/CommunityService.java

댓글 조회 API 추가
* 2023-12-27
댓글 조회 API 추가

[update] 댓글 조회 API 추가

---

src/main/java/com/sunny/backend/dto/response/community/CommunityResponse.java

게시글 조회 response 수정
* 2023-12-27
- 게시글 조회 / 댓글 조회 API 분리
- 게시글 조회 response에서 댓글 response 제외

[fix] 게시글 조회 response 수정

---

src/main/java/com/sunny/backend/controller/MyPageController.java
src/main/java/com/sunny/backend/dto/response/comment/CommentResponse.java
src/main/java/com/sunny/backend/service/MyPageService.java

마이페이지 댓글 조회 response 수정
* 2023-12-27
- 마이페이지 댓글 조회 response 수정
> 게시글 id, 댓글 시간 추가

[update] 마이페이지 댓글 조회 response 수정

---

src/main/java/com/sunny/backend/controller/NotificationController.java

알림 API 수정 ver2
* 2023-12-28
알림 API 수정 ver2

[fix] 알림 API 수정 ver2

---

src/main/java/com/sunny/backend/repository/NotificationRepository.java
src/main/java/com/sunny/backend/service/NotificationService.java

알림 API 예외 처리
* 2023-12-28
- 이미 알림을 허용했을 때 알림 토큰 저장하는 API 호출하면 예외처리
-  알림 허용하지 않은 사용자에게 알림 요청했을 때 예외처리

[update] 알림 API 예외 처리

---

src/main/java/com/sunny/backend/dto/request/chat/ChatMessageResponse.java
src/main/java/com/sunny/backend/entity/chat/ChatUser.java
src/main/java/com/sunny/backend/repository/chat/ChatMessageRepository.java
src/main/java/com/sunny/backend/repository/chat/ChatMessageRepositoryCustom.java
src/main/java/com/sunny/backend/repository/chat/ChatMessageRepositoryImpl.java
src/main/java/com/sunny/backend/repository/chat/ChatUserRepository.java
src/main/java/com/sunny/backend/service/ChatService.java

refator : chat 보내기 로직 수정

---

src/main/java/com/sunny/backend/controller/ChatRestController.java
src/main/java/com/sunny/backend/controller/NotificationController.java

refactor : Swagger 정리

---

src/main/java/com/sunny/backend/controller/CommunityController.java
src/main/java/com/sunny/backend/controller/UserProfileController.java
src/main/java/com/sunny/backend/service/UserProfileService.java
src/main/java/com/sunny/backend/service/community/CommunityService.java

친구 프로필 조회 API 수정
* 2023-12-29
친구 프로필 조회 API 수정

[update] 친구 프로필 조회 API 수정

---

src/main/java/com/sunny/backend/service/KaKaoService.java

kakao profile image 가져오기 테스트
*2023-12-29
kakao profile image 가져오기 테스트

[update] kakao profile image 가져오기

---

src/main/java/com/sunny/backend/service/KaKaoService.java

kakao 프로필 수정
* 2023-12-29
kakao 프로필 가져오기 코드 수정

[fix] kakao 프로필 수정

---

src/main/java/com/sunny/backend/dto/response/community/CommunityResponse.java
src/main/java/com/sunny/backend/entity/Community.java
src/main/java/com/sunny/backend/entity/Notification.java
src/main/java/com/sunny/backend/service/KaKaoService.java
src/main/java/com/sunny/backend/service/comment/CommentService.java
src/main/java/com/sunny/backend/service/community/CommunityService.java
src/main/java/com/sunny/backend/user/Users.java

[update] kakao 기본 프로필 이미지 설정
* 2023-12-30
[update] kakao 기본 프로필 이미지 설정
- 기본 프로필 이미지가 null 값이 아니므로 기본 프로필 이미지 url 인지 확인하는 코드 추가

[update] kakao 기본 프로필 이미지 설정

---

src/main/java/com/sunny/backend/entity/Notification.java
src/main/java/com/sunny/backend/user/Users.java

user & notification 관계 수정
* 2023-12-30
user & notification 관계 수정
- 한 사람당 여러 개의 디바이스 기기가 있을 수 있으므로 1:n 관계로 수정

[fix] user & notification 관계 수정

---

src/main/java/com/sunny/backend/dto/response/community/CommunityResponse.java

[flx] community response 수정
* 2023-12-31
community response 수정
- 닉네임 변경 후에 변경된 닉네임으로 보이도록 response 수정

[flx] community response 수정

---

src/main/java/com/sunny/backend/dto/response/community/CommunityResponse.java
src/main/java/com/sunny/backend/entity/Community.java
src/main/java/com/sunny/backend/service/community/CommunityService.java
src/main/java/com/sunny/backend/user/Users.java
src/main/java/com/sunny/backend/user/controller/AuthController.java

[fix] 수정 시간 업데이트
* 2023-12-31
게시글 수정 시 수정 시간 현재 시간으로 반영해서 변경하도록 수정

[fix] 수정 시간 업데이트

---

src/main/java/com/sunny/backend/service/comment/CommentService.java

[fix] 비밀 댓글 수정 API 업데이트
* 2024-01-04
비밀 댓글 수정 API 업데이트

[fix] 비밀 댓글 수정 API 업데이트

---

src/main/java/com/sunny/backend/service/comment/CommentService.java

[fix] 대댓글 응답 수정
* 2024-01-05
대댓글 응답 수정

[fix] 대댓글 응답 수정

---

src/main/java/com/sunny/backend/service/FriendsService.java
src/main/java/com/sunny/backend/service/MyPageService.java

[fix] 마이페이지 프로필 수정
* 2024-01-05
마이페이지 프로필 수정
- 기존 이미지 삭제 시 기본 프로필로 변경하도록 수정

[fix] 마이페이지 프로필 수정

---

src/main/java/com/sunny/backend/controller/ConsumptionController.java
src/main/java/com/sunny/backend/controller/MyPageController.java
src/main/java/com/sunny/backend/entity/Consumption.java
src/main/java/com/sunny/backend/repository/consumption/ConsumptionRepository.java
src/main/java/com/sunny/backend/service/MyPageService.java
src/main/java/com/sunny/backend/service/community/CommunityService.java
src/main/java/com/sunny/backend/service/consumption/ConsumptionService.java
src/main/java/com/sunny/backend/user/Users.java
src/main/java/com/sunny/backend/user/repository/UserRepository.java

[feat] 탈퇴 기능 추가
* 2024-01-07
- 탈퇴 기능 추가
- 지출  수정/삭제 기능 추가

[feat] 탈퇴 기능 추가

---

src/main/java/com/sunny/backend/controller/ConsumptionController.java

[fix] 지출 내역 삭제 메소드 수정
* 2024-01-07
지출 내역 삭제 메소드 수정

[fix] 지출 내역 삭제 메소드 수정

---

src/main/java/com/sunny/backend/dto/response/community/CommunityResponse.java

[fix] community 응답 수정
* 2024-01-07
community 응답 수정

[fix] community 응답 수정

---

build.gradle
src/main/java/com/sunny/backend/dto/request/FriendsApproveRequest.java
src/main/java/com/sunny/backend/friends/controller/FriendController.java
src/main/java/com/sunny/backend/friends/service/FriendService.java
src/test/java/com/sunny/backend/friends/service/FriendServiceTest.java

friend 테스트 코드 추가 및 리팩토링
* 2024/01/09
- friend 테스트 코드 및 리팩토링

feat : friend 테스트 코드 추가 및 리팩토링

---

src/main/java/com/sunny/backend/friends/controller/FriendController.java
src/main/java/com/sunny/backend/friends/service/FriendService.java
src/test/java/com/sunny/backend/friends/service/FriendServiceTest.java

feat : 친구 신청 테스트 추가

---

src/main/java/com/sunny/backend/dto/response/consumption/ConsumptionResponse.java

[refactor] 소비 API 수정 ver 2
* 2024-01-16
소비 API 수정 ver 2
- 지출 내역 response에 지출 추가

[refactor] 소비 API 수정 ver 2

---

src/main/java/com/sunny/backend/save/domain/Save.java
src/main/java/com/sunny/backend/save/service/SaveService.java

API response 수정
* 2024-01-18
API response 수정

[update] API response 수정

---

src/main/java/com/sunny/backend/community/controller/CommunityController.java
src/main/java/com/sunny/backend/community/domain/Community.java
src/main/java/com/sunny/backend/community/dto/response/CommunityResponse.java
src/main/java/com/sunny/backend/community/service/CommunityService.java

[feat] 조회수 & 댓글 수 response 분리
* 2024-01-20
[feat] 조회수 & 댓글 수 response 분리
- 일단 서버 배포해서 프론트 임시 테스트

[feat] 조회수 & 댓글 수 response 분리

---

build.gradle
src/main/java/com/sunny/backend/auth/controller/AuthController.java
src/main/java/com/sunny/backend/auth/dto/KakaoIdResponse.java
src/main/java/com/sunny/backend/auth/dto/KakaoMemberResponse.java
src/main/java/com/sunny/backend/auth/dto/OAuthToken.java
src/main/java/com/sunny/backend/auth/jwt/TokenProvider.java
src/main/java/com/sunny/backend/auth/service/AuthService.java
src/main/java/com/sunny/backend/auth/service/KakaoService.java
src/main/java/com/sunny/backend/common/ComnConstant.java
src/main/java/com/sunny/backend/common/config/RedisConfig.java
src/main/java/com/sunny/backend/community/service/CommunityService.java
src/main/java/com/sunny/backend/user/controller/UserController.java
src/main/java/com/sunny/backend/user/domain/Users.java
src/main/java/com/sunny/backend/user/repository/UserRepository.java
src/main/java/com/sunny/backend/user/service/UserService.java
src/main/java/com/sunny/backend/util/RedisUtil.java

Kakao 로그인, 로그아웃, 탈퇴, JWT 토큰 재발급 리팩토링 및 코드 수정

Feature/user Kakao 로그인, 로그아웃, 탈퇴, JWT 토큰 재발급

---

src/main/java/com/sunny/backend/comment/service/CommentService.java
src/main/java/com/sunny/backend/notification/dto/response/AlarmListResponse.java

[fix] 댓글 조회 response 수정
* 2024-01-28
[fix] 댓글 조회 response 수정

[fix] 댓글 조회 response 수정

---

src/main/java/com/sunny/backend/comment/dto/response/CommentResponse.java
src/main/java/com/sunny/backend/comment/repository/CommentCustomRepository.java
src/main/java/com/sunny/backend/comment/repository/CommentRepositoryImpl.java
src/main/java/com/sunny/backend/comment/service/CommentService.java
src/main/java/com/sunny/backend/community/dto/response/CommunityResponse.java

[update] 커뮤니티 게시판 response 수정
* 2024-01-28
- 댓글 작성자 response 수정해야 함
- 임시 테스트 때문에 잠깐 올림

[update] 커뮤니티 게시판 response 수정

---

src/main/java/com/sunny/backend/friends/controller/FriendController.java
src/main/java/com/sunny/backend/friends/exception/FriendErrorCode.java
src/main/java/com/sunny/backend/friends/service/FriendService.java
src/main/java/com/sunny/backend/notification/service/NotificationService.java

친구 알림 수정
if문도 써도되긴한데 어짜피 하드 코딩(?) 느낌 나서 그냥 각각 메소드에 title, noticeTitle, noticeBody로 지어서 했습니다.
주말에 다시 리팩토링 한 번 해볼게요
---
sendNotificationToFriends 메소드는 프론트가 상대방이 알림을 받았는지 response가 필요없지 않을 것 같아요(?)
지금 상태면 친구 (신청,삭제,승인) 하고 나서 알림이 되는 것 까지 프론트가 기다려야하니까
이걸 비동기로 처리 해야할 것 같아요
알림 부분은 제가 테스트 못해드려서 죄송하게 생각하고 있습니다...
근데 코드가 뭔가 좀 아쉬운 느낌..!
System.out.println도 안쓰게 되시면 지워주세요~

update : 친구 알림 수정

---

src/main/java/com/sunny/backend/comment/dto/response/CommentResponse.java
src/main/java/com/sunny/backend/comment/service/CommentService.java

[fix] comment api 수정
* 2024-02-03
[fix] comment api 수정

[fix] comment api 수정

---

src/main/java/com/sunny/backend/comment/domain/Comment.java
src/main/java/com/sunny/backend/comment/service/CommentService.java

[update] comment api
* 2024-02-04
[update] comment api
- branch 무조건 바꾸기..

[update] comment api

---

src/main/java/com/sunny/backend/comment/dto/response/CommentResponse.java
src/main/java/com/sunny/backend/comment/service/CommentService.java

[fix] comment api 작성자 boolean 값 수정
* 2024-02-04
[fix] comment api 작성자 boolean 값 수정

[fix] comment api 작성자 boolean

---

src/main/java/com/sunny/backend/comment/domain/Comment.java

[fix] commet entity 수정
* 2024-02-06
[fix] commet entity 수정

[fix] commet entity 수정

---

src/main/java/com/sunny/backend/comment/domain/Comment.java

[fix] comment entity
* 2024-02-06
[fix] comment entity

[fix] comment entity

---

src/main/java/com/sunny/backend/user/dto/response/UserCommentResponse.java
src/main/java/com/sunny/backend/user/dto/response/UserCommunityResponse.java
src/main/java/com/sunny/backend/user/dto/response/UserScrapResponse.java

feat : userId 추가

---

src/main/java/com/sunny/backend/comment/repository/CommentCustomRepository.java
src/main/java/com/sunny/backend/comment/repository/CommentRepositoryImpl.java
src/main/java/com/sunny/backend/comment/service/CommentService.java
src/main/java/com/sunny/backend/common/config/BatchConfig.java
src/main/java/com/sunny/backend/community/service/CommunityService.java
src/main/java/com/sunny/backend/friends/controller/FriendController.java
src/main/java/com/sunny/backend/friends/service/FriendService.java
src/main/java/com/sunny/backend/notification/service/NotificationService.java
src/main/java/com/sunny/backend/save/controller/SaveController.java
src/main/java/com/sunny/backend/save/domain/Save.java
src/main/java/com/sunny/backend/save/dto/response/SaveResponse.java
src/main/java/com/sunny/backend/save/service/SaveService.java
src/main/java/com/sunny/backend/user/domain/Users.java

[update] comment 필요 없는 코드 제거
* 2024-02-19
comment 필요 없는 코드 제거

[update] comment 필요 없는 코드 제거

---

src/main/java/com/sunny/backend/common/exception/ErrorResponseHandler.java
src/main/java/com/sunny/backend/competition/controller/CompetitionController.java
src/main/java/com/sunny/backend/competition/dto/request/CompetitionRequest.java
src/main/java/com/sunny/backend/competition/dto/response/CompetitionStatusResponse.java
src/main/java/com/sunny/backend/competition/service/CompetitionService.java
src/main/java/com/sunny/backend/friends/dto/response/FriendResponse.java
src/main/java/com/sunny/backend/friends/repository/FriendRepositoryImpl.java
src/main/java/com/sunny/backend/friends/service/FriendService.java

feat: 상태 변경

---

src/main/java/com/sunny/backend/auth/dto/AppleTokenResponse.java
src/main/java/com/sunny/backend/community/service/CommunityService.java
src/main/java/com/sunny/backend/notification/domain/CommentNotification.java
src/main/java/com/sunny/backend/notification/dto/request/NotificationRequest.java

[chore] 임시 response
* 2024-03-04

[chore] 임시 response

---

src/main/java/com/sunny/backend/BackendApplication.java

[chore] build test

---

build.gradle
src/main/java/com/sunny/backend/BackendApplication.java
src/test/java/com/sunny/backend/BackendApplicationTests.java

[chore] test 수정

---

src/main/java/com/sunny/backend/friends/service/FriendService.java
src/main/java/com/sunny/backend/save/service/SaveService.java

[fix] 친구 예외 처리 추가

---

build.gradle
src/main/java/com/sunny/backend/AppConfig.java
src/main/java/com/sunny/backend/HttpClientUtils.java
src/main/java/com/sunny/backend/auth/AppleController.java
src/main/java/com/sunny/backend/auth/AppleFeignClientConfiguration.java
src/main/java/com/sunny/backend/auth/AppleService.java
src/main/java/com/sunny/backend/auth/dto/AppleAuthClient.java
src/main/java/com/sunny/backend/auth/dto/AppleTokenResponse.java
src/main/java/com/sunny/backend/notification/dto/request/NotificationPushRequest.java
src/main/java/com/sunny/backend/user/controller/UserController.java
src/main/java/com/sunny/backend/user/service/UserService.java

[feat] apple login ver2
* 2024-03-09
- 애플 로그인 test ver2

[feat] apple login ver2

---

src/main/java/com/sunny/backend/auth/AppleService.java
src/main/java/com/sunny/backend/user/service/UserService.java

[fix] 신고 알림 API 수정
* 2024-03-09
신고 배너 알림 API 수정

[fix] 신고 알림 API 수정

---

src/main/java/com/sunny/backend/competition/service/CompetitionService.java

[update] 대결 신청 배너 알림 수정
* YYYY/MM/DD

[update] 대결 신청 배너 알림 수정

---

src/main/java/com/sunny/backend/notification/controller/NotificationController.java
src/main/java/com/sunny/backend/notification/service/NotificationService.java

[update] 알림 허용 get method 추가
* 2024-03-12
알림 허용 get method 추가

[update] 알림 허용 get method 추가

---

src/main/java/com/sunny/backend/auth/AppleController.java

[chore] apple login test 주석 추가

---

src/main/java/com/sunny/backend/auth/AppleService.java
src/main/java/com/sunny/backend/common/config/SecurityConfig.java

[chore] apple login test 주석추가

---

.gitignore
src/main/java/com/sunny/backend/auth/AppleController.java
src/main/java/com/sunny/backend/auth/AppleOAuthClient.java
src/main/java/com/sunny/backend/auth/AppleOAuthPublicKeyGenerator.java
src/main/java/com/sunny/backend/auth/AppleRevokeRequest.java
src/main/java/com/sunny/backend/auth/AppleService.java
src/main/java/com/sunny/backend/auth/OAuth2Client.java
src/main/java/com/sunny/backend/auth/dto/AppleAuthClient.java

[chore] git ignore 설정

---

src/main/java/com/sunny/backend/apple/AppleController.java

[chore] 탈퇴 log 추가

---

src/main/java/com/sunny/backend/apple/AppleService.java

[update] 탈퇴 API 수정

---

src/main/java/com/sunny/backend/apple/AppleService.java

[chore] 탈퇴 API

---

src/main/java/com/sunny/backend/apple/AppleController.java
src/main/java/com/sunny/backend/apple/AppleService.java
src/main/java/com/sunny/backend/auth/dto/TokenResponse.java
src/main/java/com/sunny/backend/auth/dto/UserRequest.java
src/main/java/com/sunny/backend/auth/jwt/CustomJwtFilter.java
src/main/java/com/sunny/backend/auth/jwt/TokenProvider.java

[feat] apple logout API test
* 2024-03-21
[feat] apple logout API test ver1

[feat] apple logout API test

---

src/main/java/com/sunny/backend/auth/jwt/TokenProvider.java

[chore] test api

---

src/main/java/com/sunny/backend/auth/jwt/CustomJwtFilter.java

[chore] logout test

---

src/main/java/com/sunny/backend/auth/jwt/CustomJwtFilter.java

[chore] logout test ver 2

---

src/main/java/com/sunny/backend/apple/AppleService.java
src/main/java/com/sunny/backend/auth/jwt/TokenProvider.java

[chore] logout test ver 3

---

src/main/java/com/sunny/backend/apple/AppleController.java

[chore] logout test ver 4

---

src/main/java/com/sunny/backend/auth/jwt/CustomJwtFilter.java

[chore] logout test ver 5

---

src/main/java/com/sunny/backend/apple/AppleController.java
src/main/java/com/sunny/backend/apple/AppleOAuthClient.java
src/main/java/com/sunny/backend/comment/dto/response/CommentResponse.java
src/main/java/com/sunny/backend/comment/service/CommentService.java

[update] comment response 수정

---

src/main/java/com/sunny/backend/auth/controller/AuthController.java
src/main/java/com/sunny/backend/auth/service/KakaoService.java

[update] kakao login 임시 추가
* 2024-03-22
kakao login API 임시 추가

[update] kakao login 임시 추가

---

src/main/java/com/sunny/backend/apple/AppleController.java
src/main/java/com/sunny/backend/apple/AppleService.java
src/main/java/com/sunny/backend/auth/jwt/TokenProvider.java

[update] apple logout api
* 2024-03-22
apple logout api 추가
- 로그아웃시 redis accessToken blacklist 추가

[update] apple logout api

---

src/main/java/com/sunny/backend/auth/jwt/TokenProvider.java
src/main/java/com/sunny/backend/common/config/RedisConfig.java

[update] apple logout api ver 2

---

src/main/java/com/sunny/backend/apple/AppleController.java
src/main/java/com/sunny/backend/apple/AppleService.java
src/main/java/com/sunny/backend/auth/dto/UserRequest.java
src/main/java/com/sunny/backend/auth/jwt/CustomJwtFilter.java
src/main/java/com/sunny/backend/auth/jwt/TokenProvider.java
src/main/java/com/sunny/backend/common/config/RedisConfig.java
src/main/java/com/sunny/backend/util/RedisUtil.java

[update] apple logout api ver 3
* 2024-03-22
apple logout api ver 3
- logout 시 accessToken redis blacklist 추가
- 기존 accessToken 으로 접근 불가

[update] apple logout api ver 3

---

src/main/java/com/sunny/backend/competition/domain/CompetitionOutput.java
src/main/java/com/sunny/backend/competition/service/CompetitionService.java

refactor : 대결 거절 API 수정

---

src/main/java/com/sunny/backend/competition/dto/response/CompetitionStatusResponse.java
src/main/java/com/sunny/backend/competition/service/CompetitionService.java

[update] 대결 response 수정
* 2024-03-25
- 대결 현황 API호출 시 상대방, 사용자 지출 % response 수정
- TODO
- 상대방, 사용자 지출 % 계산 메소드 분리해야 함

[update] 대결 response 수정

---

src/main/java/com/sunny/backend/competition/domain/Competition.java
src/main/java/com/sunny/backend/competition/domain/CompetitionOutputType.java
src/main/java/com/sunny/backend/competition/exception/CompetitionErrorCode.java
src/main/java/com/sunny/backend/competition/service/CompetitionService.java
src/main/java/com/sunny/backend/friends/domain/Friend.java
src/main/java/com/sunny/backend/friends/domain/FriendStatus.java
src/main/java/com/sunny/backend/friends/dto/response/FriendCompetitionResponse.java
src/main/java/com/sunny/backend/friends/dto/response/FriendListResponse.java
src/main/java/com/sunny/backend/friends/exception/FriendErrorCode.java
src/main/java/com/sunny/backend/friends/repository/FriendCustomRepository.java
src/main/java/com/sunny/backend/friends/repository/FriendRepositoryImpl.java
src/main/java/com/sunny/backend/friends/service/FriendService.java

feat : 친구 추가 시 SEND, RECEIVE 형태로 수정

---

src/main/java/com/sunny/backend/competition/domain/Competition.java
src/main/java/com/sunny/backend/competition/exception/CompetitionErrorCode.java
src/main/java/com/sunny/backend/competition/service/CompetitionService.java

feat : 본인이 신청하고 본인이 승인/거절 불가능 처리

---

src/main/java/com/sunny/backend/competition/service/CompetitionService.java
src/main/java/com/sunny/backend/save/domain/Save.java

[update] save response 수정

---

src/main/java/com/sunny/backend/save/dto/response/SaveResponse.java
src/main/java/com/sunny/backend/save/service/SaveService.java

[update] save 날짜 한글 설정

---

src/main/java/com/sunny/backend/competition/dto/response/CompetitionApplyResponse.java
src/main/java/com/sunny/backend/competition/service/CompetitionService.java
src/main/java/com/sunny/backend/friends/controller/FriendController.java
src/main/java/com/sunny/backend/friends/service/FriendService.java
src/main/java/com/sunny/backend/notification/dto/response/AlarmListResponse.java
src/main/java/com/sunny/backend/notification/repository/FriendsNotificationRepository.java
src/main/java/com/sunny/backend/notification/service/NotificationService.java

[update] 배너 알림 & 알림 리스트 response 수정
* 2024-03-27
- 대결 / 친구 배너 알림 response 수정
- refactoring 전에 알림 제대로 오는지 테스트 한 것만 push

[update] 배너 알림 & 알림 리스트 response 수정

---

src/main/java/com/sunny/backend/consumption/repository/ConsumptionRepositoryImpl.java
src/main/java/com/sunny/backend/save/service/SaveService.java

[update] save 퍼센트 계산 수정

---

src/main/java/com/sunny/backend/apple/AppleController.java

[chore] 탈퇴 API 로그 추가
* 2024-03-28
탈퇴 API 로그 추가

[chore] 탈퇴 API 로그 추가

---

src/main/java/com/sunny/backend/apple/AppleService.java

[chore] 탈퇴 API log 추가

---

src/main/java/com/sunny/backend/apple/AppleController.java
src/main/java/com/sunny/backend/apple/AppleService.java

[feat] apple_login 탈퇴 API 수정
* 2024-03-28
apple_login 탈퇴 API 수정 
- RestTemplate 대신 feign 이용해서 해보기

[feat] apple_login 탈퇴 API 수정 완료

---

src/main/java/com/sunny/backend/apple/AppleService.java

[chore] apple_login 탈퇴 API log

---

src/main/java/com/sunny/backend/apple/AppleService.java

[update] apple 탈퇴 log 추가

---

src/main/java/com/sunny/backend/apple/AppleService.java
src/main/java/com/sunny/backend/comment/service/CommentService.java

[update] 댓글 삭제 API 수정
* 2024-03-31
댓글 삭제 API 수정

[update] 댓글 삭제 API 수정

---

src/main/java/com/sunny/backend/apple/AppleController.java
src/main/java/com/sunny/backend/apple/AppleService.java

[update] apple 탈퇴 API 수정

---

src/main/java/com/sunny/backend/notification/service/NotificationService.java

[update] 댓글 알림 리스트 수정

---

src/main/java/com/sunny/backend/comment/dto/response/CommentResponse.java
src/main/java/com/sunny/backend/comment/service/CommentService.java

[update] 탈퇴 유무 response 추가

---

src/main/java/com/sunny/backend/competition/service/CompetitionService.java
src/main/java/com/sunny/backend/friends/service/FriendService.java
src/main/java/com/sunny/backend/notification/domain/CompetitionNotification.java
src/main/java/com/sunny/backend/notification/dto/response/AlarmListResponse.java
src/main/java/com/sunny/backend/notification/service/NotificationService.java

[update] 알림 response 수정
* 2024-04-02
- 알림 response 고유 Id 추가
- 알림 response 이름 동적 처리

[update] 알림 response 수정

---

src/main/java/com/sunny/backend/competition/service/CompetitionService.java
src/main/java/com/sunny/backend/friends/service/FriendService.java

[update] 알림 배너 수정

---

src/main/java/com/sunny/backend/competition/service/CompetitionService.java
src/main/java/com/sunny/backend/friends/service/FriendService.java

[update] 배너 알림 수정

---

src/main/java/com/sunny/backend/competition/service/CompetitionService.java
src/main/java/com/sunny/backend/friends/service/FriendService.java

[update] 대결 배너 알림 수정

---

src/main/java/com/sunny/backend/competition/service/CompetitionService.java

[chore] 대결 신청 배너 수정
* YYYY/MM/DD

[chore] 대결 신청 배너 수정

---

src/main/java/com/sunny/backend/competition/service/CompetitionService.java

[update] 대결 배너 알림 수정 최종

---

src/main/java/com/sunny/backend/competition/service/CompetitionService.java
src/main/java/com/sunny/backend/friends/service/FriendService.java

[chore] 필요없는 주석 삭제

---

src/main/java/com/sunny/backend/friends/service/FriendService.java

[chore] 사용하지 않는 메서드 삭제

---

src/main/java/com/sunny/backend/competition/service/CompetitionService.java
src/main/java/com/sunny/backend/friends/service/FriendService.java
src/main/java/com/sunny/backend/notification/service/NotificationService.java

[chore] 사용하지 않는 주석 & 메서드 삭제
* 2024-04-02
사용하지 않는 주석 & 메서드 삭제

[chore] 사용하지 않는 주석 & 메서드 삭제

---

src/main/java/com/sunny/backend/community/dto/request/CommunityRequest.java
src/main/java/com/sunny/backend/competition/service/CompetitionService.java
src/main/java/com/sunny/backend/friends/service/FriendService.java
src/main/java/com/sunny/backend/notification/domain/CompetitionNotification.java
src/main/java/com/sunny/backend/notification/domain/Notification.java
src/main/java/com/sunny/backend/notification/service/NotificationService.java
src/main/java/com/sunny/backend/save/service/SaveService.java

[update] 알림 수정
* 2024-04-03
- 알림 수정
- 절약 목표 response 수정

[update] 알림 수정

---

src/main/java/com/sunny/backend/apple/AppleOAuthClient.java
src/main/java/com/sunny/backend/auth/jwt/CustomUserPrincipal.java
src/main/java/com/sunny/backend/auth/service/KakaoService.java
src/main/java/com/sunny/backend/community/domain/Community.java
src/main/java/com/sunny/backend/community/service/CommunityService.java
src/main/java/com/sunny/backend/competition/service/CompetitionService.java
src/main/java/com/sunny/backend/friends/domain/Friend.java
src/main/java/com/sunny/backend/friends/service/FriendService.java
src/main/java/com/sunny/backend/notification/domain/FriendsNotification.java
src/main/java/com/sunny/backend/notification/domain/Notification.java
src/main/java/com/sunny/backend/notification/dto/response/AlarmListResponse.java
src/main/java/com/sunny/backend/notification/repository/FriendsNotificationRepository.java
src/main/java/com/sunny/backend/notification/service/FriendNotiService.java
src/main/java/com/sunny/backend/notification/service/NotificationService.java
src/main/java/com/sunny/backend/save/domain/Save.java
src/main/java/com/sunny/backend/user/domain/UserReport.java
src/main/java/com/sunny/backend/user/domain/Users.java

refactor : db 수정

---

src/main/java/com/sunny/backend/apple/AppleService.java
src/main/java/com/sunny/backend/consumption/dto/response/SaveGoalAlertResponse.java
src/main/java/com/sunny/backend/consumption/service/ConsumptionService.java
src/main/java/com/sunny/backend/notification/repository/CommentNotificationRepository.java
src/main/java/com/sunny/backend/notification/repository/CompetitionNotificationRepository.java
src/main/java/com/sunny/backend/notification/repository/FriendsNotificationRepository.java
src/main/java/com/sunny/backend/notification/repository/NotificationRepository.java
src/main/java/com/sunny/backend/notification/service/NotificationService.java

알람 먼저 삭제만 추가
---
지출 등록시 목표 금액 넘은 경우 소 사용하여 알림 전송 추가

feat : apple 탈퇴 시 알람 먼저 삭제

---

src/main/java/com/sunny/backend/notification/dto/response/AlarmListResponse.java
src/main/java/com/sunny/backend/notification/service/NotificationService.java

[update] 알림 리스트 정렬
* 2024-04-11
- 최신 알림이 상단에 보이도록 알림 리스트 정렬 조건 추가
- 알림 response 수정
- 사용하지 않는 메서드 삭제

[update] 알림 리스트 정렬

---

src/main/java/com/sunny/backend/consumption/controller/ConsumptionController.java
src/main/java/com/sunny/backend/consumption/service/ConsumptionService.java

[update] 지출 등록 response 삭제
* 2024-04-12
지출 등록 response 삭제

[update] 지출 등록 response 삭제

---

src/main/java/com/sunny/backend/consumption/service/ConsumptionService.java
src/main/java/com/sunny/backend/notification/service/FriendNotiService.java

[update] 대결 결과 배너 알림 추가

---

src/main/java/com/sunny/backend/competition/service/CompetitionScheduleService.java
src/main/java/com/sunny/backend/consumption/service/ConsumptionService.java

[update] 대결 소켓 배너 알림 추가

---

src/main/java/com/sunny/backend/competition/service/CompetitionScheduleService.java
src/main/java/com/sunny/backend/competition/service/CompetitionService.java
src/main/java/com/sunny/backend/consumption/controller/ConsumptionController.java
src/main/java/com/sunny/backend/consumption/service/ConsumptionService.java
src/main/java/com/sunny/backend/notification/domain/CompetitionNotification.java
src/main/java/com/sunny/backend/notification/dto/response/AlarmListResponse.java
src/main/java/com/sunny/backend/notification/service/FriendNotiService.java
src/main/java/com/sunny/backend/notification/service/NotificationService.java

[update] 알림 리스트 수정

---

src/main/java/com/sunny/backend/apple/service/AppleService.java
src/main/java/com/sunny/backend/competition/service/CompetitionScheduleService.java
src/main/java/com/sunny/backend/competition/service/CompetitionService.java
src/main/java/com/sunny/backend/friends/repository/FriendCompetitionRepository.java
src/main/java/com/sunny/backend/notification/dto/response/AlarmListResponse.java
src/main/java/com/sunny/backend/notification/service/FriendNotiService.java

[update] 대결 포기 알림 추가
* 2024-04-14
- 대결 포기 알림 추가
- 커뮤니티 댓글 알림에 유저 아이디 추가

[update] 대결 포기 알림 추가

---

src/main/java/com/sunny/backend/user/dto/response/UserCommentResponse.java

[update] 비밀 댓글 수정

---

src/main/java/com/sunny/backend/user/dto/response/UserCommentResponse.java

[update] 댓글 response 수정

---

src/main/java/com/sunny/backend/comment/service/CommentService.java
src/main/java/com/sunny/backend/common/config/BatchConfig.java
src/main/java/com/sunny/backend/competition/service/CompetitionService.java
src/main/java/com/sunny/backend/notification/domain/CommentNotification.java
src/main/java/com/sunny/backend/notification/domain/CompetitionNotification.java
src/main/java/com/sunny/backend/notification/domain/FriendsNotification.java
src/main/java/com/sunny/backend/notification/dto/response/AlarmListResponse.java
src/main/java/com/sunny/backend/notification/repository/CommentNotificationRepository.java
src/main/java/com/sunny/backend/notification/service/FriendNotiService.java
src/main/java/com/sunny/backend/notification/service/NotificationService.java

[update] 알림 리스트 response 추가
* 2024-04-17
- 경쟁 받은 여부,경쟁 진행 여부, 친구 여부 response 추가

[update] 알림 리스트 response 추가

---

naver-checkstyle-rules.xml
src/main/java/com/sunny/backend/community/repository/CommunityRepositoryImpl.java
src/main/java/com/sunny/backend/user/controller/UserController.java
src/main/java/com/sunny/backend/user/domain/Block.java
src/main/java/com/sunny/backend/user/domain/Users.java
src/main/java/com/sunny/backend/user/repository/BlockRepository.java
src/main/java/com/sunny/backend/user/service/UserService.java

[feat] 상대방 차단 기능 추가
* 2024-04-18
- 상대방 차단 기능 추가
- 차단한 상대방 게시글 보이지 않도록 API 추가
- 차단 도메인 추가

[feat] 상대방 차단 기능 추가

---

src/main/java/com/sunny/backend/notification/domain/NotifiacationSubType.java
src/main/java/com/sunny/backend/notification/domain/NotificationType.java
src/main/java/com/sunny/backend/notification/domain/UserReportNotification.java
src/main/java/com/sunny/backend/notification/dto/response/AlarmListResponse.java
src/main/java/com/sunny/backend/notification/repository/UserReportNotificationRepository.java
src/main/java/com/sunny/backend/notification/service/FriendNotiService.java
src/main/java/com/sunny/backend/notification/service/NotificationService.java
src/main/java/com/sunny/backend/report/service/CommentReportService.java
src/main/java/com/sunny/backend/report/service/CommunityReportService.java
src/main/java/com/sunny/backend/report/service/ReportNotificationService.java
src/main/java/com/sunny/backend/report/service/ReportService.java

[update] 댓글 신고 response 추가
* 2024-04-19
댓글/커뮤 신고 response 추가

[update] 댓글 신고 response 추가

---

src/main/java/com/sunny/backend/notification/dto/response/AlarmListResponse.java

[update] 신고 알림 response 유저 추가

---

src/main/java/com/sunny/backend/report/service/CommentReportService.java
src/main/java/com/sunny/backend/report/service/CommunityReportService.java
src/main/java/com/sunny/backend/report/service/ReportNotificationService.java

[fix] 신고 배너 알림 수정

---

src/main/java/com/sunny/backend/apple/service/AppleService.java
src/main/java/com/sunny/backend/notification/repository/UserReportNotificationRepository.java

[update] 탈퇴 로직 추가
* 2024-04-19
- 탈퇴 로직 추가
- 탈퇴 시 신고 알림 지우기

[update] 탈퇴 로직 추가

---

src/main/java/com/sunny/backend/comment/service/CommentService.java

[update] 탈퇴한 회원의 댓글 response 수정

---

src/main/java/com/sunny/backend/comment/service/CommentService.java

[fix] 댓글 작성자 유무 response 수정

---

src/main/java/com/sunny/backend/comment/service/CommentService.java
src/main/java/com/sunny/backend/community/service/CommunityService.java
src/main/java/com/sunny/backend/report/repository/CommentReportRepository.java
src/main/java/com/sunny/backend/report/repository/CommunityReportRepository.java

게시글 삭제 API 수정
* 2024-04-20
- 게시글, 게시글 댓글에 신고 기록이 있을 경우 게시글 삭제가 되지 않았음
- 에러 해결

[fix] 게시글 삭제 API 수정

---

src/main/java/com/sunny/backend/comment/service/CommentService.java
src/main/java/com/sunny/backend/user/exception/BlockListErrorCode.java
src/main/java/com/sunny/backend/user/service/UserService.java

[fix] 차단 당한 유저 response 수정
* 2024-04-21
차단 당한 유저 response 수정

[fix] 차단 당한 유저 response 수정

---

src/main/java/com/sunny/backend/comment/service/CommentService.java
src/main/java/com/sunny/backend/user/service/UserService.java

[update] 차단 api 수정

---

src/main/java/com/sunny/backend/friends/service/FriendService.java
src/main/java/com/sunny/backend/user/dto/response/ProfileResponse.java

feat: 유저 닉네임 누락 추가

---

build.gradle

[merge] dev main code merge
* 2024-04-29
- 써니 프로젝트 최신 메인 코드 업데이트

[merge] dev main code merge

---

src/main/java/com/sunny/backend/apple/controller/AppleController.java
src/main/java/com/sunny/backend/user/domain/Users.java

[fix] 닉네임 설정 api 수정

---

src/main/java/com/sunny/backend/apple/service/AppleOAuthClient.java
src/main/java/com/sunny/backend/user/domain/Users.java

[fix] 랜덤 유저 닉네임 API 수정
* 2024-05-31
- 랜덤 유저 닉네임 2~10글자 이내로 생성하도록 수정

[fix] 랜덤 유저 닉네임 API 수정
